name: CI/CD

on:
    push:
        branches: [master]

jobs:
    build:
        name: Build the app
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm install

            - run: npm run lint

            - run: npm run build

            - name: Copy CNAME
              run: cp CNAME dist/

              # SPA support on Github Pages
            - name: Copy index.html to 404.html
              run: cp dist/index.html dist/404.html

            - uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist

    deploy:
        name: Deploy to Github Pages
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/download-artifact@v2

            - name: Commit and push to gh-pages
              run: |
                  cd dist

                  git init
                  git config user.name "GitHub Actions"
                  git config user.email "<>"
                  git add --all
                  git commit --message 'deploy'

                  REPO="https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
                  git push --force $REPO master:gh-pages
