name: CI/CD

on:
    push:
        branches: [master]

jobs:
    build:
        name: Build the app
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm install

            - run: npm run lint

            - run: npm run build

            - uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist

    deploy:
        name: Deploy to Github Pages
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/download-artifact@v2

            - run: |
                  cd dist
                  git add --all
                  git commit --message 'deploy'
                  git push -f git@github.com:martindzejky/tekwoo.sk.git master:gh-pages
